# ABOUTME: goreleaser configuration for cross-platform binary distribution
# ABOUTME: Builds pi-go for linux/darwin/windows on amd64/arm64

version: 2

builds:
  - id: pi-go
    main: ./cmd/pi-go
    binary: pi-go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: pi-go
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
