// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package openai

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(in *jlexer.Lexer, out *toolCallFuncDelta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "arguments":
			out.Arguments = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(out *jwriter.Writer, in toolCallFuncDelta) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Arguments != "" {
		const prefix string = ",\"arguments\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Arguments))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v toolCallFuncDelta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v toolCallFuncDelta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *toolCallFuncDelta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *toolCallFuncDelta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai(l, v)
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(in *jlexer.Lexer, out *toolCallDelta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = int(in.Int())
		case "id":
			out.ID = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "function":
			(out.Function).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(out *jwriter.Writer, in toolCallDelta) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	if in.ID != "" {
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	if in.Type != "" {
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"function\":"
		out.RawString(prefix)
		(in.Function).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v toolCallDelta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v toolCallDelta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *toolCallDelta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *toolCallDelta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai1(l, v)
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(in *jlexer.Lexer, out *chunkUsage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "prompt_tokens":
			out.PromptTokens = int(in.Int())
		case "completion_tokens":
			out.CompletionTokens = int(in.Int())
		case "total_tokens":
			out.TotalTokens = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(out *jwriter.Writer, in chunkUsage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"prompt_tokens\":"
		out.RawString(prefix[1:])
		out.Int(int(in.PromptTokens))
	}
	{
		const prefix string = ",\"completion_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.CompletionTokens))
	}
	{
		const prefix string = ",\"total_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.TotalTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v chunkUsage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v chunkUsage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *chunkUsage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *chunkUsage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai2(l, v)
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(in *jlexer.Lexer, out *chunkDelta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "role":
			out.Role = string(in.String())
		case "content":
			out.Content = string(in.String())
		case "tool_calls":
			if in.IsNull() {
				in.Skip()
				out.ToolCalls = nil
			} else {
				in.Delim('[')
				if out.ToolCalls == nil {
					if !in.IsDelim(']') {
						out.ToolCalls = make([]toolCallDelta, 0, 0)
					} else {
						out.ToolCalls = []toolCallDelta{}
					}
				} else {
					out.ToolCalls = (out.ToolCalls)[:0]
				}
				for !in.IsDelim(']') {
					var v1 toolCallDelta
					(v1).UnmarshalEasyJSON(in)
					out.ToolCalls = append(out.ToolCalls, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(out *jwriter.Writer, in chunkDelta) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Role != "" {
		const prefix string = ",\"role\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Content))
	}
	if len(in.ToolCalls) != 0 {
		const prefix string = ",\"tool_calls\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.ToolCalls {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v chunkDelta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v chunkDelta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *chunkDelta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *chunkDelta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai3(l, v)
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(in *jlexer.Lexer, out *chunkChoice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = int(in.Int())
		case "delta":
			(out.Delta).UnmarshalEasyJSON(in)
		case "finish_reason":
			out.FinishReason = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(out *jwriter.Writer, in chunkChoice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"delta\":"
		out.RawString(prefix)
		(in.Delta).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"finish_reason\":"
		out.RawString(prefix)
		out.String(string(in.FinishReason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v chunkChoice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v chunkChoice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *chunkChoice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *chunkChoice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai4(l, v)
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(in *jlexer.Lexer, out *chatCompletionChunk) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "choices":
			if in.IsNull() {
				in.Skip()
				out.Choices = nil
			} else {
				in.Delim('[')
				if out.Choices == nil {
					if !in.IsDelim(']') {
						out.Choices = make([]chunkChoice, 0, 0)
					} else {
						out.Choices = []chunkChoice{}
					}
				} else {
					out.Choices = (out.Choices)[:0]
				}
				for !in.IsDelim(']') {
					var v4 chunkChoice
					(v4).UnmarshalEasyJSON(in)
					out.Choices = append(out.Choices, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				out.Usage = nil
			} else {
				if out.Usage == nil {
					out.Usage = new(chunkUsage)
				}
				(*out.Usage).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(out *jwriter.Writer, in chatCompletionChunk) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"choices\":"
		out.RawString(prefix)
		if in.Choices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Choices {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Usage != nil {
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		(*in.Usage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v chatCompletionChunk) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v chatCompletionChunk) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *chatCompletionChunk) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *chatCompletionChunk) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderOpenai5(l, v)
}
