// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package anthropic

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	ai "github.com/mauromedda/pi-coding-agent-go/pkg/ai"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(in *jlexer.Lexer, out *sseErrorPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			easyjson5f687493Decode(in, &out.Error)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(out *jwriter.Writer, in sseErrorPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		easyjson5f687493Encode(out, in.Error)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sseErrorPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sseErrorPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sseErrorPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sseErrorPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic(l, v)
}
func easyjson5f687493Decode(in *jlexer.Lexer, out *struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode(out *jwriter.Writer, in struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(in *jlexer.Lexer, out *messageStartPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			easyjson5f687493Decode1(in, &out.Message)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(out *jwriter.Writer, in messageStartPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		easyjson5f687493Encode1(out, in.Message)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v messageStartPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v messageStartPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *messageStartPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *messageStartPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic1(l, v)
}
func easyjson5f687493Decode1(in *jlexer.Lexer, out *struct {
	Model string   `json:"model"`
	Usage ai.Usage `json:"usage"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "model":
			out.Model = string(in.String())
		case "usage":
			easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAi(in, &out.Usage)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode1(out *jwriter.Writer, in struct {
	Model string   `json:"model"`
	Usage ai.Usage `json:"usage"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAi(out, in.Usage)
	}
	out.RawByte('}')
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAi(in *jlexer.Lexer, out *ai.Usage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "input_tokens":
			out.InputTokens = int(in.Int())
		case "output_tokens":
			out.OutputTokens = int(in.Int())
		case "cache_read_input_tokens":
			out.CacheRead = int(in.Int())
		case "cache_creation_input_tokens":
			out.CacheCreate = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAi(out *jwriter.Writer, in ai.Usage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"input_tokens\":"
		out.RawString(prefix[1:])
		out.Int(int(in.InputTokens))
	}
	{
		const prefix string = ",\"output_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.OutputTokens))
	}
	if in.CacheRead != 0 {
		const prefix string = ",\"cache_read_input_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.CacheRead))
	}
	if in.CacheCreate != 0 {
		const prefix string = ",\"cache_creation_input_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.CacheCreate))
	}
	out.RawByte('}')
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(in *jlexer.Lexer, out *messageDeltaPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "delta":
			easyjson5f687493Decode2(in, &out.Delta)
		case "usage":
			easyjson5f687493Decode3(in, &out.Usage)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(out *jwriter.Writer, in messageDeltaPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"delta\":"
		out.RawString(prefix[1:])
		easyjson5f687493Encode2(out, in.Delta)
	}
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		easyjson5f687493Encode3(out, in.Usage)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v messageDeltaPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v messageDeltaPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *messageDeltaPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *messageDeltaPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic2(l, v)
}
func easyjson5f687493Decode3(in *jlexer.Lexer, out *struct {
	OutputTokens int `json:"output_tokens"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "output_tokens":
			out.OutputTokens = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode3(out *jwriter.Writer, in struct {
	OutputTokens int `json:"output_tokens"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"output_tokens\":"
		out.RawString(prefix[1:])
		out.Int(int(in.OutputTokens))
	}
	out.RawByte('}')
}
func easyjson5f687493Decode2(in *jlexer.Lexer, out *struct {
	StopReason ai.StopReason `json:"stop_reason"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "stop_reason":
			out.StopReason = ai.StopReason(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode2(out *jwriter.Writer, in struct {
	StopReason ai.StopReason `json:"stop_reason"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"stop_reason\":"
		out.RawString(prefix[1:])
		out.String(string(in.StopReason))
	}
	out.RawByte('}')
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(in *jlexer.Lexer, out *contentBlockStartPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = int(in.Int())
		case "content_block":
			easyjson5f687493Decode4(in, &out.ContentBlock)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(out *jwriter.Writer, in contentBlockStartPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"content_block\":"
		out.RawString(prefix)
		easyjson5f687493Encode4(out, in.ContentBlock)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v contentBlockStartPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v contentBlockStartPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *contentBlockStartPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *contentBlockStartPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic3(l, v)
}
func easyjson5f687493Decode4(in *jlexer.Lexer, out *struct {
	Type string `json:"type"`
	ID   string `json:"id"`
	Name string `json:"name"`
	Text string `json:"text"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "id":
			out.ID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "text":
			out.Text = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode4(out *jwriter.Writer, in struct {
	Type string `json:"type"`
	ID   string `json:"id"`
	Name string `json:"name"`
	Text string `json:"text"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(in *jlexer.Lexer, out *contentBlockDeltaPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "delta":
			easyjson5f687493Decode5(in, &out.Delta)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(out *jwriter.Writer, in contentBlockDeltaPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"delta\":"
		out.RawString(prefix[1:])
		easyjson5f687493Encode5(out, in.Delta)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v contentBlockDeltaPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v contentBlockDeltaPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5f687493EncodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *contentBlockDeltaPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *contentBlockDeltaPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5f687493DecodeGithubComMauromeddaPiCodingAgentGoPkgAiProviderAnthropic4(l, v)
}
func easyjson5f687493Decode5(in *jlexer.Lexer, out *struct {
	Type        string `json:"type"`
	Text        string `json:"text"`
	PartialJSON string `json:"partial_json"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "text":
			out.Text = string(in.String())
		case "partial_json":
			out.PartialJSON = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5f687493Encode5(out *jwriter.Writer, in struct {
	Type        string `json:"type"`
	Text        string `json:"text"`
	PartialJSON string `json:"partial_json"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"partial_json\":"
		out.RawString(prefix)
		out.String(string(in.PartialJSON))
	}
	out.RawByte('}')
}
